version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: /docker-entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - appdata:/code/data
      - appfiles:/code/files
      - appstatic:/code/static
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
volumes:
  appdata:
  appfiles:
  appstatic: