# Generated by Django 4.2.23 on 2026-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='id',
            field=models.CharField(choices=[('vocals-dog-control', 'Vocalizations'), ('right-lung-dog-control', 'Right Lung Sound'), ('left-lung-dog-control', 'Left Lung Sound'), ('left-femoral-pulse-dog-control', 'Left Femoral Pulse'), ('right-femoral-pulse-dog-control', 'Right Femoral Pulse'), ('left-dorsal-pulse-dog-control', 'Left Dorsal Pulse'), ('right-dorsal-pulse-dog-control', 'Right Dorsal Pulse'), ('heart-sound-dog-control', 'Heart Sounds'), ('chest-dog-control', 'Chest Movement'), ('button-cpr', 'Cpr'), ('button-ekg', 'Ekg'), ('button-SpO2', 'Spo2'), ('button-CO2', 'Etco2'), ('button-bpcuff', 'Cuff'), ('button-palpate', 'Palpate'), ('button-Tperi', 'Temp')], default='vocals-dog-control', max_length=32),
        ),
        migrations.AlterField(
            model_name='summary',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='summary',
            name='symptoms',
            field=models.TextField(blank=True, default='Scenario Symptoms'),
        ),
        migrations.AlterField(
            model_name='trigger',
            name='test',
            field=models.CharField(blank=True, choices=[('EQ', 'Eq'), ('GT', 'Gt'), ('LT', 'Lt'), ('LTE', 'Lte'), ('GTE', 'Gte'), ('INSIDE', 'Inside'), ('OUTSIDE', 'Outside'), ('', 'None')], default='', max_length=7, null=True),
        ),
    ]
