# Generated by Django 4.2.23 on 2026-09-06 18:36

import app.storage
import app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_control_id_alter_summary_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocalfile',
            name='filename',
            field=models.FileField(storage=app.storage.OverwriteStorage(), upload_to=app.storage.vocals_upload_to, validators=[app.validators.validate_wav_extension]),
        ),
    ]
