name: Django CI

on:
  push:
    branches: [ main, poc ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install Dependencies
      working-directory: backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      working-directory: backend
      env:
        DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
      run: |
        python manage.py test